CREATE TABLE IF NOT EXISTS person
(
    person_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username  varchar UNIQUE NOT NULL CHECK (length(username) > 3 AND length(username) < 56),
    email     varchar UNIQUE NOT NULL CHECK (length(email) > 3 AND length(email) < 56),
    password  varchar        NOT NULL,
    role      varchar        NOT NULL
);