services:
  postgres-auth:
    image: postgres:latest
    container_name: auth-service-db
    hostname: postgres-auth
    restart: always
    environment:
      POSTGRES_DB: auth-service
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 9qwe1ox
    ports:
      - "5433:5432"
    networks:
      - capsule
    volumes:
      - postgres-auth-data:/var/lib/postgresql/data

  postgres-account:
    image: postgres:latest
    container_name: account-service-db
    hostname: postgres-account
    restart: always
    environment:
      POSTGRES_DB: account-service
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 9qwe1ox
    ports:
      - "5434:5432"
    networks:
      - capsule
    volumes:
      - postgres-account-data:/var/lib/postgresql/data

  postgres-email-verify:
    image: postgres:latest
    container_name: email-verify-service-db
    hostname: postgres-email-verify
    restart: always
    environment:
      POSTGRES_DB: email-verify-service
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 9qwe1ox
    ports:
      - "5435:5432"
    networks:
      - capsule
    volumes:
      - postgres-email-verify-data:/var/lib/postgresql/data

  postgres-statistics:
    image: postgres:latest
    container_name: statistics-service-db
    hostname: postgres-statistics
    restart: always
    environment:
      POSTGRES_DB: statistics-service
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 9qwe1ox
    ports:
      - "5436:5432"
    networks:
      - capsule
    volumes:
      - postgres-statistics-data:/var/lib/postgresql/data

  postgres-tasks:
    image: postgres:latest
    container_name: tasks-service-db
    hostname: postgres-tasks
    restart: always
    environment:
      POSTGRES_DB: tasks-service
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 9qwe1ox
    ports:
      - "5437:5432"
    networks:
      - capsule
    volumes:
      - postgres-tasks-data:/var/lib/postgresql/data

  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    restart: always
    environment:
      ZOO_MY_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - capsule

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    hostname: kafka
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    networks:
      - capsule

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    hostname: kafka-ui
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    ports:
      - "8090:8080"
    links:
      - kafka
      - zookeeper
    networks:
      - capsule

  eureka-server:
    image: trapperumin/eureka-server:latest
    container_name: eureka-server
    hostname: eureka-server
    restart: always
    environment:
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
    ports:
      - "8761:8761"
    networks:
      - capsule

  api-gateway:
    image: trapperumin/api-gateway:latest
    container_name: api-gateway
    hostname: api-gateway
    restart: always
    environment:
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - capsule

  auth-service:
    image: trapperumin/auth-service:latest
    container_name: auth-service
    hostname: auth-service
    restart: always
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      POSTGRES_USERNAME: root
      POSTGRES_PASSWORD: 9qwe1ox
      POSTGRES_AUTH_URL: jdbc:postgresql://postgres-auth:5432/auth-service
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - eureka-server
      - postgres-auth
    networks:
      - capsule

  account-management-service:
    image: trapperumin/account-management-service:latest
    container_name: account-management-service
    hostname: account-management-service
    restart: always
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      POSTGRES_USERNAME: root
      POSTGRES_PASSWORD: 9qwe1ox
      POSTGRES_ACCOUNT_URL: jdbc:postgresql://postgres-account:5432/account-service
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - eureka-server
      - postgres-account
    networks:
      - capsule

  assay-passing-service:
    image: trapperumin/assay-passing-service:latest
    container_name: assay-passing-service
    hostname: assay-passing-service
    restart: always
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - eureka-server
    networks:
      - capsule

  statistics-service:
    image: trapperumin/statistics-service:latest
    container_name: statistics-service
    hostname: statistics-service
    restart: always
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      POSTGRES_USERNAME: root
      POSTGRES_PASSWORD: 9qwe1ox
      POSTGRES_ACCOUNT_URL: jdbc:postgresql://postgres-statistics:5432/statistics-service
    ports:
      - "8084:8084"
    depends_on:
      - kafka
      - eureka-server
      - postgres-statistics
    networks:
      - capsule

  tasks-service:
    image: trapperumin/tasks-service:latest
    container_name: tasks-service
    hostname: tasks-service
    restart: always
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      POSTGRES_USERNAME: root
      POSTGRES_PASSWORD: 9qwe1ox
      POSTGRES_ACCOUNT_URL: jdbc:postgresql://postgres-tasks:5432/tasks-service
    ports:
      - "8085:8085"
    depends_on:
      - kafka
      - eureka-server
      - postgres-tasks
    networks:
      - capsule

  email-verify-service:
    image: trapperumin/email-verify-service:latest
    container_name: email-verify-service
    hostname: email-verify-service
    restart: always
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      POSTGRES_USERNAME: root
      POSTGRES_PASSWORD: 9qwe1ox
      POSTGRES_ACCOUNT_URL: jdbc:postgresql://postgres-email-verify:5432/email-verify-service
    ports:
      - "8088:8088"
    depends_on:
      - kafka
      - eureka-server
      - postgres-email-verify
    networks:
      - capsule

  email-verify-sender-service:
    image: trapperumin/email-verify-sender-service:latest
    container_name: email-verify-sender-service
    hostname: email-verify-sender-service
    restart: always
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
    ports:
      - "8089:8089"
    depends_on:
      - kafka
      - eureka-server
    networks:
      - capsule

networks:
  capsule:
    driver: bridge

volumes:
  postgres-auth-data:
  postgres-account-data:
  postgres-statistics-data:
  postgres-tasks-data:
  postgres-email-verify-data:
  zookeeper-data:
  zookeeper-log:
  kafka-data: