CREATE TABLE IF NOT EXISTS details
(
    details_id  bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username    varchar   NOT NULL,
    first_name  varchar CHECK ( length(first_name) < 128 ),
    second_name varchar CHECK ( length(second_name) < 128 ),
    age         int CHECK (age > 0 AND age < 128),
    created_at  timestamp NOT NULL,
    updated_at  timestamp NOT NULL
);