CREATE SCHEMA IF NOT EXISTS task;

CREATE TYPE task_status AS ENUM ('IN PROGRESS', 'COMPLETE', 'SKIP');

CREATE TABLE IF NOT EXISTS task
(
    task_id     bigint       NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title       varchar(52)  NOT NULL,
    description varchar(140) NOT NULL
);
CREATE TABLE IF NOT EXISTS tasks_manage
(
    task_manage_id bigint      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    task_id        bigint      NOT NULL,
    username       varchar     NOT NULL,
    status         task_status NOT NULL
);