CREATE TABLE IF NOT EXISTS statistic
(
    statistic_id    bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username        varchar NOT NULL,
    score           int DEFAULT 0 CHECK ( score >= 0 ),
    missed_tasks    int DEFAULT 0 CHECK ( missed_tasks >= 0 ),
    completed_tasks int DEFAULT 0 CHECK ( completed_tasks >= 0 )
)